"""
Smart Agriculture Knowledge Base
Contains agronomic rules, curated crop requirements, soil health benchmarks,
fertilizer guidance, seasonal schedules, and pest/disease diagnostic data.
"""

# Curated crop database containing optimal environmental & soil parameters
CROP_DATABASE = {
    "rice": {
        "name": "Rice (Paddy)",
        "category": "Cereal / Grain",
        "season": ["Kharif", "Monsoon", "Summer"],
        "min_temp": 20, "max_temp": 38, "optimal_temp": 26,
        "min_rainfall": 1000, "max_rainfall": 3000, "optimal_rainfall": 1750,
        "min_ph": 5.5, "max_ph": 7.5, "optimal_ph": 6.5,
        "soil_types": ["Clayey", "Alluvial", "Clay Loam", "Loamy"],
        "npk_requirement": {"N": 80, "P": 40, "K": 40},
        "growth_duration_days": "110 - 150 days",
        "water_management": "Requires standing water (2-5 cm) during early growth stages. Substantial irrigation needed.",
        "fertilizer_recommendation": "Apply 50% N, 100% P, and 100% K at basal; remaining N split into tillering and panicle initiation stages.",
        "common_diseases": ["Blast", "Bacterial Leaf Blight", "Sheath Blight", "Brown Spot"],
        "pests": ["Stem Borer", "Brown Planthopper", "Gall Midge"],
        "yield_potential": "4.5 - 6.5 tonnes / hectare",
        "market_advice": "High demand staple crop. Best sold through grain mandis or direct mill contracts.",
        "icon": "🌾"
    },
    "wheat": {
        "name": "Wheat",
        "category": "Cereal / Grain",
        "season": ["Rabi", "Winter"],
        "min_temp": 10, "max_temp": 25, "optimal_temp": 18,
        "min_rainfall": 350, "max_rainfall": 750, "optimal_rainfall": 500,
        "min_ph": 6.0, "max_ph": 7.5, "optimal_ph": 6.8,
        "soil_types": ["Alluvial", "Clay Loam", "Loamy", "Black Soil"],
        "npk_requirement": {"N": 120, "P": 60, "K": 40},
        "growth_duration_days": "100 - 130 days",
        "water_management": "Critical irrigation stages: Crown root initiation (21 days), Tillering, Flowering, and Milking stages.",
        "fertilizer_recommendation": "Full P & K at sowing + 1/2 N. Remaining N applied after first irrigation.",
        "common_diseases": ["Yellow Rust", "Brown Rust", "Loose Smut", "Karnal Bunt"],
        "pests": ["Aphids", "Armyworm", "Termites"],
        "yield_potential": "4.0 - 5.5 tonnes / hectare",
        "market_advice": "Winter staple with reliable government MSP and flour mill procurement demand.",
        "icon": "🌾"
    },
    "maize": {
        "name": "Maize (Corn)",
        "category": "Coarse Cereal",
        "season": ["Kharif", "Rabi", "Spring"],
        "min_temp": 18, "max_temp": 35, "optimal_temp": 24,
        "min_rainfall": 500, "max_rainfall": 1000, "optimal_rainfall": 650,
        "min_ph": 5.8, "max_ph": 7.8, "optimal_ph": 6.5,
        "soil_types": ["Sandy Loam", "Loamy", "Alluvial", "Red Soil"],
        "npk_requirement": {"N": 120, "P": 60, "K": 50},
        "growth_duration_days": "90 - 110 days",
        "water_management": "Sensitive to waterlogging. Ensure proper drainage. Irrigate at tasseling and silking.",
        "fertilizer_recommendation": "Split Nitrogen into 3 doses (sowing, knee-high stage, and tasseling stage).",
        "common_diseases": ["Maydis Leaf Blight", "Turcicum Blight", "Downy Mildew"],
        "pests": ["Fall Armyworm", "Stem Borer"],
        "yield_potential": "5.0 - 7.0 tonnes / hectare",
        "market_advice": "High industrial demand for poultry feed, starch manufacturing, and ethanol production.",
        "icon": "🌽"
    },
    "cotton": {
        "name": "Cotton",
        "category": "Cash / Fiber Crop",
        "season": ["Kharif", "Summer"],
        "min_temp": 21, "max_temp": 38, "optimal_temp": 28,
        "min_rainfall": 500, "max_rainfall": 1100, "optimal_rainfall": 750,
        "min_ph": 6.0, "max_ph": 8.0, "optimal_ph": 7.0,
        "soil_types": ["Black Soil (Regur)", "Alluvial", "Clay Loam"],
        "npk_requirement": {"N": 100, "P": 50, "K": 50},
        "growth_duration_days": "150 - 180 days",
        "water_management": "Deep root system. Requires moisture at squaring and boll formation; dry weather during boll opening.",
        "fertilizer_recommendation": "Foliar spray of 2% DAP or Potassium Nitrate at flowering improves boll retention.",
        "common_diseases": ["Bacterial Blight", "Alternaria Leaf Spot", "Fusarium Wilt"],
        "pests": ["Pink Bollworm", "Whitefly", "Thrips", "Jassids"],
        "yield_potential": "2.0 - 3.5 tonnes / hectare",
        "market_advice": "Premium cash crop; monitor global commodity pricing and lint quality benchmarks.",
        "icon": "☁️"
    },
    "sugarcane": {
        "name": "Sugarcane",
        "category": "Commercial / Sugar Crop",
        "season": ["Annual", "Spring", "Autumn"],
        "min_temp": 20, "max_temp": 38, "optimal_temp": 30,
        "min_rainfall": 1200, "max_rainfall": 2500, "optimal_rainfall": 1800,
        "min_ph": 6.0, "max_ph": 8.0, "optimal_ph": 6.8,
        "soil_types": ["Deep Loamy", "Black Soil", "Alluvial"],
        "npk_requirement": {"N": 250, "P": 100, "K": 120},
        "growth_duration_days": "300 - 365 days",
        "water_management": "High water consumer. Drip irrigation can reduce water usage by 40-50% while boosting yield.",
        "fertilizer_recommendation": "Heavy nitrogen consumer; split N across 45, 90, and 120 days after planting.",
        "common_diseases": ["Red Rot", "Smut", "Wilt", "Grassy Shoot"],
        "pests": ["Early Shoot Borer", "Top Borer", "White Grub"],
        "yield_potential": "80 - 110 tonnes / hectare",
        "market_advice": "Tied directly to local sugar mills and jaggery processing units.",
        "icon": "🎋"
    },
    "chickpea": {
        "name": "Chickpea (Gram)",
        "category": "Pulse / Legume",
        "season": ["Rabi", "Winter"],
        "min_temp": 12, "max_temp": 28, "optimal_temp": 20,
        "min_rainfall": 300, "max_rainfall": 650, "optimal_rainfall": 450,
        "min_ph": 6.0, "max_ph": 8.0, "optimal_ph": 7.0,
        "soil_types": ["Sandy Loam", "Clay Loam", "Black Soil"],
        "npk_requirement": {"N": 20, "P": 40, "K": 20},
        "growth_duration_days": "90 - 120 days",
        "water_management": "Drought tolerant. Needs only 1-2 irrigations (branching and pod development stage).",
        "fertilizer_recommendation": "Low nitrogen requirement due to biological N-fixation. Inoculate seeds with Rhizobium.",
        "common_diseases": ["Ascochyta Blight", "Fusarium Wilt", "Dry Root Rot"],
        "pests": ["Helicoverpa (Gram Pod Borer)", "Cutworm"],
        "yield_potential": "1.8 - 2.5 tonnes / hectare",
        "market_advice": "High protein legume with steady domestic pulse market demand.",
        "icon": "🌱"
    },
    "tomato": {
        "name": "Tomato",
        "category": "Horticulture / Vegetable",
        "season": ["Kharif", "Rabi", "Summer"],
        "min_temp": 15, "max_temp": 32, "optimal_temp": 22,
        "min_rainfall": 400, "max_rainfall": 900, "optimal_rainfall": 600,
        "min_ph": 6.0, "max_ph": 7.5, "optimal_ph": 6.5,
        "soil_types": ["Sandy Loam", "Loamy", "Rich Organic Soil"],
        "npk_requirement": {"N": 100, "P": 60, "K": 80},
        "growth_duration_days": "70 - 90 days after transplant",
        "water_management": "Regular, uniform watering prevents blossom end rot and fruit cracking. Drip irrigation ideal.",
        "fertilizer_recommendation": "Apply well-decomposed Farmyard Manure (FYM) + Calcium Nitrate during fruiting.",
        "common_diseases": ["Early Blight", "Late Blight", "Tomato Leaf Curl Virus (TLCV)"],
        "pests": ["Fruit Borer", "Whitefly", "Leafminer"],
        "yield_potential": "25 - 40 tonnes / hectare",
        "market_advice": "Highly perishable; consider local wholesale mandi vs cold chain retail.",
        "icon": "🍅"
    },
    "potato": {
        "name": "Potato",
        "category": "Tuber / Vegetable",
        "season": ["Rabi", "Winter", "Autumn"],
        "min_temp": 12, "max_temp": 25, "optimal_temp": 18,
        "min_rainfall": 400, "max_rainfall": 700, "optimal_rainfall": 500,
        "min_ph": 5.2, "max_ph": 6.8, "optimal_ph": 5.8,
        "soil_types": ["Sandy Loam", "Alluvial", "Loose Loamy"],
        "npk_requirement": {"N": 150, "P": 80, "K": 100},
        "growth_duration_days": "80 - 110 days",
        "water_management": "Keep soil moist but not soggy. Stop irrigation 10-14 days before harvest.",
        "fertilizer_recommendation": "High potassium booster for tuber size and starch content.",
        "common_diseases": ["Late Blight", "Early Blight", "Common Scab", "Black Scurf"],
        "pests": ["Potato Tuber Moth", "Aphids"],
        "yield_potential": "20 - 35 tonnes / hectare",
        "market_advice": "Requires cold storage infrastructure for counter-seasonal price optimization.",
        "icon": "🥔"
    },
    "soybean": {
        "name": "Soybean",
        "category": "Oilseed / Legume",
        "season": ["Kharif", "Monsoon"],
        "min_temp": 20, "max_temp": 32, "optimal_temp": 26,
        "min_rainfall": 600, "max_rainfall": 1000, "optimal_rainfall": 800,
        "min_ph": 6.0, "max_ph": 7.5, "optimal_ph": 6.5,
        "soil_types": ["Black Soil", "Loamy", "Clay Loam"],
        "npk_requirement": {"N": 30, "P": 60, "K": 40},
        "growth_duration_days": "90 - 110 days",
        "water_management": "Critical moisture needed at flowering and pod filling stages.",
        "fertilizer_recommendation": "Seed treatment with Rhizobium japonicum + PSB (Phosphate Solubilizing Bacteria).",
        "common_diseases": ["Yellow Mosaic Virus", "Charcoal Rot", "Rust"],
        "pests": ["Girdle Beetle", "Stem Fly", "Tobacco Caterpillar"],
        "yield_potential": "2.2 - 3.2 tonnes / hectare",
        "market_advice": "Strong oil extraction and soy meal feed export market.",
        "icon": "🌱"
    },
    "banana": {
        "name": "Banana",
        "category": "Fruit / Commercial",
        "season": ["Annual", "Year-round"],
        "min_temp": 20, "max_temp": 38, "optimal_temp": 27,
        "min_rainfall": 1200, "max_rainfall": 2200, "optimal_rainfall": 1600,
        "min_ph": 5.8, "max_ph": 7.8, "optimal_ph": 6.5,
        "soil_types": ["Deep Alluvial", "Clay Loam", "Rich Organic"],
        "npk_requirement": {"N": 200, "P": 50, "K": 300},
        "growth_duration_days": "300 - 360 days",
        "water_management": "High water requirement. Drip fertigation is standard practice.",
        "fertilizer_recommendation": "Heavy Potassium feeder. Apply split doses every 30-45 days until shooting.",
        "common_diseases": ["Panama Wilt (Fusarium)", "Sigatoka Leaf Spot", "Banana Bunchy Top"],
        "pests": ["Banana Weevil", "Nematodes"],
        "yield_potential": "40 - 70 tonnes / hectare",
        "market_advice": "Continuous harvesting fruit with fast turnaround and domestic year-round consumption.",
        "icon": "🍌"
    },
    "mango": {
        "name": "Mango",
        "category": "Fruit / Perennial",
        "season": ["Perennial", "Summer Harvest"],
        "min_temp": 22, "max_temp": 42, "optimal_temp": 28,
        "min_rainfall": 500, "max_rainfall": 1500, "optimal_rainfall": 900,
        "min_ph": 5.5, "max_ph": 7.5, "optimal_ph": 6.5,
        "soil_types": ["Alluvial", "Red Sandy Loam", "Deep Loamy"],
        "npk_requirement": {"N": 100, "P": 50, "K": 100},
        "growth_duration_days": "Perennial (Flowers Dec-Feb, Harvests Apr-Jul)",
        "water_management": "Withhold water 2-3 months before flowering to induce flower bud differentiation.",
        "fertilizer_recommendation": "Apply manures and fertilizers immediately after fruit harvest and pruning in monsoon.",
        "common_diseases": ["Powdery Mildew", "Anthracnose", "Dieback"],
        "pests": ["Mango Hopper", "Fruit Fly", "Stem Borer"],
        "yield_potential": "8 - 15 tonnes / hectare",
        "market_advice": "High value export crop (Alphonso, Kesar, Dasheri) with seasonal spikes.",
        "icon": "🥭"
    },
    "coffee": {
        "name": "Coffee (Arabica / Robusta)",
        "category": "Plantation / Beverage",
        "season": ["Perennial", "Winter Harvest"],
        "min_temp": 15, "max_temp": 28, "optimal_temp": 22,
        "min_rainfall": 1200, "max_rainfall": 2500, "optimal_rainfall": 1800,
        "min_ph": 5.0, "max_ph": 6.5, "optimal_ph": 5.8,
        "soil_types": ["Deep Forest Loam", "Volcanic Red Soil", "Laterite"],
        "npk_requirement": {"N": 140, "P": 90, "K": 130},
        "growth_duration_days": "Perennial (Berry maturation 8-9 months)",
        "water_management": "Blossom showers in March-April critical for fruit set.",
        "fertilizer_recommendation": "Pre-monsoon and post-monsoon split application with micronutrients (Zinc, Boron).",
        "common_diseases": ["Coffee Leaf Rust (Hemileia vastatrix)", "Black Rot", "Anthracnose"],
        "pests": ["Coffee White Stem Borer", "Coffee Berry Borer"],
        "yield_potential": "1.0 - 2.0 tonnes clean coffee / hectare",
        "market_advice": "Export-oriented commodity. Certified organic / shade-grown earns high premiums.",
        "icon": "☕"
    },
    "apple": {
        "name": "Apple",
        "category": "Temperate Fruit / Orchard",
        "season": ["Temperate / Autumn Harvest"],
        "min_temp": 5, "max_temp": 22, "optimal_temp": 15,
        "min_rainfall": 800, "max_rainfall": 1200, "optimal_rainfall": 1000,
        "min_ph": 5.5, "max_ph": 6.8, "optimal_ph": 6.0,
        "soil_types": ["Loamy", "Deep Mountain Soil", "Well-drained Gravelly Loam"],
        "npk_requirement": {"N": 70, "P": 35, "K": 70},
        "growth_duration_days": "Perennial (Requires 800-1200 chilling hours < 7°C)",
        "water_management": "Critical moisture during fruit enlargement and shoot growth stages.",
        "fertilizer_recommendation": "Boron and Calcium sprays prevent internal browning and bitter pit.",
        "common_diseases": ["Apple Scab", "Powdery Mildew", "Fire Blight"],
        "pests": ["Woolly Apple Aphid", "San Jose Scale", "Mites"],
        "yield_potential": "10 - 20 tonnes / hectare",
        "market_advice": "Requires grading, waxing, and cold chain distribution for best retail margins.",
        "icon": "🍎"
    },
    "watermelon": {
        "name": "Watermelon",
        "category": "Cucurbit / Fruit",
        "season": ["Zaid", "Summer"],
        "min_temp": 24, "max_temp": 38, "optimal_temp": 30,
        "min_rainfall": 300, "max_rainfall": 600, "optimal_rainfall": 450,
        "min_ph": 6.0, "max_ph": 7.5, "optimal_ph": 6.5,
        "soil_types": ["Sandy Loam", "Riverbed Alluvial", "Light Loam"],
        "npk_requirement": {"N": 80, "P": 50, "K": 50},
        "growth_duration_days": "80 - 100 days",
        "water_management": "Frequent light watering; reduce water 10 days before harvest to enhance sweetness.",
        "fertilizer_recommendation": "Mulching and potassium fertigation enhance brix (sugar) levels.",
        "common_diseases": ["Fusarium Wilt", "Downy Mildew", "Anthracnose"],
        "pests": ["Red Pumpkin Beetle", "Fruit Fly", "Aphids"],
        "yield_potential": "25 - 45 tonnes / hectare",
        "market_advice": "Peak demand during hot summer months; harvest at full slip for sweetness.",
        "icon": "🍉"
    },
    "onion": {
        "name": "Onion",
        "category": "Bulb / Vegetable",
        "season": ["Kharif", "Late Kharif", "Rabi"],
        "min_temp": 13, "max_temp": 30, "optimal_temp": 20,
        "min_rainfall": 400, "max_rainfall": 800, "optimal_rainfall": 550,
        "min_ph": 6.0, "max_ph": 7.5, "optimal_ph": 6.8,
        "soil_types": ["Sandy Loam", "Clay Loam", "Alluvial"],
        "npk_requirement": {"N": 100, "P": 50, "K": 60},
        "growth_duration_days": "120 - 150 days",
        "water_management": "Shallow root system; requires light, frequent irrigations. Stop 15 days before lifting.",
        "fertilizer_recommendation": "Sulphur application (20-30 kg/ha) enhances pungency, color, and storage shelf-life.",
        "common_diseases": ["Purple Blotch", "Stemphylium Leaf Blight", "Basal Rot"],
        "pests": ["Onion Thrips", "Maggots"],
        "yield_potential": "18 - 30 tonnes / hectare",
        "market_advice": "Subject to price volatility; dry thoroughly in shade before ventilated storage.",
        "icon": "🧅"
    }
}

# Soil Types reference guide
SOIL_DATABASE = {
    "Alluvial": {
        "characteristics": "Formed by river silt deposits; rich in potash, phosphoric acid, and lime; light to medium texture.",
        "water_retention": "Moderate to High",
        "drainage": "Good",
        "ph_typical": "6.5 - 7.8",
        "best_crops": ["Rice", "Wheat", "Sugarcane", "Maize", "Cotton", "Potato", "Vegetables"],
        "soil_enhancement": "Incorporate green manure and compost to maintain organic carbon."
    },
    "Black Soil (Regur)": {
        "characteristics": "High clay content (montmorillonite), self-ploughing property (shrinks and cracks when dry), rich in calcium, potassium, and magnesium.",
        "water_retention": "Very High",
        "drainage": "Poor when saturated",
        "ph_typical": "7.2 - 8.5",
        "best_crops": ["Cotton", "Soybean", "Sugarcane", "Wheat", "Chickpea", "Sorghum"],
        "soil_enhancement": "Improve drainage using raised beds or ridge-and-furrow systems. Avoid over-irrigation."
    },
    "Sandy Loam": {
        "characteristics": "Warm, fast-draining, easy to cultivate, good aeration, low native organic matter.",
        "water_retention": "Low to Moderate",
        "drainage": "Excellent",
        "ph_typical": "6.0 - 7.0",
        "best_crops": ["Watermelon", "Tomato", "Potato", "Groundnut", "Maize", "Carrot"],
        "soil_enhancement": "Apply heavy doses of Farmyard Manure (FYM) or biochar to increase water holding capacity."
    },
    "Clay Loam": {
        "characteristics": "Balanced blend of clay, silt, and sand; fertile with strong nutrient holding capacity.",
        "water_retention": "High",
        "drainage": "Moderate",
        "ph_typical": "6.2 - 7.5",
        "best_crops": ["Wheat", "Rice", "Sugarcane", "Soybean", "Pulses", "Vegetables"],
        "soil_enhancement": "Maintain microbial activity with vermicompost and crop residue mulching."
    },
    "Red Soil": {
        "characteristics": "Rich in iron oxides (gives red color), porous and friable structure, typically deficient in nitrogen, phosphorus, and humus.",
        "water_retention": "Moderate",
        "drainage": "Good",
        "ph_typical": "5.5 - 6.8",
        "best_crops": ["Mango", "Groundnut", "Maize", "Millets", "Tobacco", "Pulses"],
        "soil_enhancement": "Regular application of lime to correct acidity, plus NPK and organic compost."
    },
    "Laterite": {
        "characteristics": "Formed in intense tropical rainfall regions; heavily leached; rich in iron and aluminum; acidic.",
        "water_retention": "Low",
        "drainage": "High",
        "ph_typical": "4.8 - 6.0",
        "best_crops": ["Coffee", "Tea", "Cashew", "Rubber", "Coconut"],
        "soil_enhancement": "Apply agricultural lime or dolomite to neutralize acidity; heavy organic inputs."
    }
}

# Symptom-to-Disease Knowledge Base
DISEASE_DIAGNOSIS_RULES = [
    {
        "id": "blast_rice",
        "crop": "Rice",
        "symptoms": ["Spindle-shaped or diamond spots with grey centers on leaves", "Rotting at neck node causing panicle to drop"],
        "diagnosis": "Rice Blast (Magnaporthe oryzae fungus)",
        "urgency": "High",
        "chemical_control": "Spray Tricyclazole 75% WP @ 0.6 g/L or Azoxystrobin 23% SC @ 1 ml/L.",
        "organic_control": "Foliar spray of Pseudomonas fluorescens @ 5 g/L; avoid excessive nitrogen fertilizer.",
        "preventive_tips": "Treat seeds with Carbendazim before sowing; maintain field sanitation."
    },
    {
        "id": "rust_wheat",
        "crop": "Wheat",
        "symptoms": ["Yellow, orange or reddish-brown powdery pustules in lines or clusters on leaves", "Premature drying of leaf canopy"],
        "diagnosis": "Wheat Rust (Yellow / Brown Rust - Puccinia spp.)",
        "urgency": "High",
        "chemical_control": "Spray Propiconazole 25% EC (Tilt) @ 1 ml/L at first appearance.",
        "organic_control": "Spray Neem oil 3000 ppm @ 3 ml/L; plant rust-resistant certified cultivars.",
        "preventive_tips": "Plant early to avoid late winter humidity spikes; monitor cooler canopy areas."
    },
    {
        "id": "armyworm_maize",
        "crop": "Maize",
        "symptoms": ["Ragged feeding holes in leaves", "Sawdust-like frass (excrement) inside leaf whorls", "Damaged growing shoot tips"],
        "diagnosis": "Fall Armyworm (Spodoptera frugiperda)",
        "urgency": "Critical",
        "chemical_control": "Spray Emamectin Benzoate 5% SG @ 0.4 g/L or Chlorantraniliprole 18.5% SC @ 0.3 ml/L into the whorl.",
        "organic_control": "Apply Bacillus thuringiensis (Bt) kurstaki @ 2 g/L or release Trichogramma egg parasitoids.",
        "preventive_tips": "Install pheromone traps @ 5 per acre for early pest population surveillance."
    },
    {
        "id": "late_blight_potato_tomato",
        "crop": "Potato / Tomato",
        "symptoms": ["Water-soaked dark lesions on leaf tips turning necrotic rapidly", "White fuzzy mold on underside of leaves in humid mornings", "Brown rotting patches on tubers/fruits"],
        "diagnosis": "Late Blight (Phytophthora infestans)",
        "urgency": "Critical",
        "chemical_control": "Prophylactic spray of Mancozeb 75% WP @ 2.5 g/L; curative spray with Metalaxyl-M + Mancozeb @ 2 g/L.",
        "organic_control": "Copper Oxychloride spray @ 2.5 g/L; destroy infected plant debris immediately.",
        "preventive_tips": "Ensure wide plant spacing for airflow; avoid overhead sprinkler watering."
    },
    {
        "id": "bollworm_cotton",
        "crop": "Cotton",
        "symptoms": ["Bored holes in bolls with larval excreta", "Flared squares (rosetted flowers)", "Premature shedding of young bolls"],
        "diagnosis": "Pink Bollworm (Pectinophora gossypiella)",
        "urgency": "High",
        "chemical_control": "Spray Profenofos 50% EC @ 2 ml/L or Spinosad 45% SC @ 0.35 ml/L.",
        "organic_control": "Install mating disruption PB-Rope dispensers @ 100/acre; spray Beauveria bassiana.",
        "preventive_tips": "Strictly follow 120-150 days closed season; avoid ratoon cotton farming."
    },
    {
        "id": "leaf_curl_tomato",
        "crop": "Tomato",
        "symptoms": ["Upward curling and puckering of leaves", "Stunted bush-like plant growth", "Thickened vein network and poor fruit set"],
        "diagnosis": "Tomato Leaf Curl Virus (transmitted by Whiteflies)",
        "urgency": "Medium",
        "chemical_control": "Control whitefly vector with Acetamiprid 20% SP @ 0.3 g/L or Diafenthiuron 50% WP @ 1 g/L.",
        "organic_control": "Install yellow sticky traps @ 15/acre; spray 10% cow urine or neem seed kernel extract (NSKE 5%).",
        "preventive_tips": "Use nylon insect-proof net (40-50 mesh) for seedling nursery protection."
    }
]
